from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    dependencies = [("core", "0002_learningpost_analytics"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="ProjectMilestone", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=160)), ("is_complete", models.BooleanField(default=False)), ("completed_at", models.DateTimeField(blank=True, null=True)), ("position", models.PositiveSmallIntegerField(default=0)), ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="milestones", to="core.project"))], options={"ordering": ["position", "id"]}),
        migrations.CreateModel(name="ActivityEvent", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("event_type", models.CharField(choices=[("project", "Project"), ("learning", "Learning"), ("network", "Network"), ("profile", "Profile"), ("login", "Login")], max_length=20)), ("action", models.CharField(max_length=80)), ("points", models.PositiveSmallIntegerField(default=1)), ("metadata", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activity_events", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="ContentView", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("session_key", models.CharField(max_length=40)), ("viewed_on", models.DateField(auto_now_add=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="unique_views", to="core.learningpost")), ("viewer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="content_views", to=settings.AUTH_USER_MODEL))], options={"constraints": [models.UniqueConstraint(fields=("post", "session_key", "viewed_on"), name="unique_daily_content_view")]}),
        migrations.CreateModel(name="DailyLoopCompletion", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("step", models.CharField(choices=[("build", "Build"), ("learn", "Learn"), ("share", "Share")], max_length=10)), ("completed_on", models.DateField()), ("created_at", models.DateTimeField(auto_now_add=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_loop_completions", to=settings.AUTH_USER_MODEL))], options={"constraints": [models.UniqueConstraint(fields=("user", "step", "completed_on"), name="unique_daily_loop_step")]}),
        migrations.CreateModel(name="EarningTransaction", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("transaction_type", models.CharField(choices=[("credit", "Credit"), ("payout", "Payout"), ("adjustment", "Adjustment")], default="credit", max_length=20)), ("amount", models.DecimalField(decimal_places=2, max_digits=10)), ("description", models.CharField(max_length=180)), ("created_at", models.DateTimeField(auto_now_add=True)), ("post", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="earning_transactions", to="core.learningpost")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="earning_transactions", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
    ]
