from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
class Migration(migrations.Migration):
    dependencies = [("core", "0003_activity_analytics"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Repository", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("slug", models.SlugField(max_length=100)), ("storage_key", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)), ("default_branch", models.CharField(default="main", max_length=100)), ("visibility", models.CharField(choices=[("private", "Private"), ("public", "Public")], default="private", max_length=10)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="repositories", to=settings.AUTH_USER_MODEL)), ("project", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="repository", to="core.project"))], options={"constraints": [models.UniqueConstraint(fields=("owner", "slug"), name="unique_owner_repository_slug")]}),
        migrations.CreateModel(name="GitAccessToken", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80)), ("prefix", models.CharField(db_index=True, max_length=12)), ("token_hash", models.CharField(max_length=64)), ("scope", models.CharField(choices=[("read", "Read repositories"), ("write", "Read and write repositories")], default="write", max_length=10)), ("expires_at", models.DateTimeField(blank=True, null=True)), ("last_used_at", models.DateTimeField(blank=True, null=True)), ("revoked_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="git_tokens", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="RepositoryCollaborator", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("role", models.CharField(choices=[("read", "Read"), ("write", "Write"), ("maintain", "Maintain")], default="read", max_length=10)), ("created_at", models.DateTimeField(auto_now_add=True)), ("repository", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="collaborators", to="core.repository")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="repository_memberships", to=settings.AUTH_USER_MODEL))], options={"constraints": [models.UniqueConstraint(fields=("repository", "user"), name="unique_repository_collaborator")]}),
    ]
